#!/usr/bin/env bash
# Usage: exenv version-file [<dir>]
# Summary: Detect the file that sets the current exenv version
set -e
[ -n "$EXENV_DEBUG" ] && set -x

target_dir="$1"

find_local_version_file() {
  local root="$1"
  while ! [[ "$root" =~ ^//[^/]*$ ]]; do
    if [ -e "${root}/.elixir-version" ]; then
      echo "${root}/.elixir-version"
      return 0
    fi
    [ -n "$root" ] || break
    root="${root%/*}"
  done
  return 1
}

if [ -n "$target_dir" ]; then
  find_local_version_file "$target_dir"
else
  find_local_version_file "$EXENV_DIR" || {
    [ "$EXENV_DIR" != "$PWD" ] && find_local_version_file "$PWD"
  } || echo "${EXENV_ROOT}/version"
fi
