#!/usr/bin/env bash
# Usage: exenv version-file-write <file> <version>

set -e
[ -n "$EXENV_DEBUG" ] && set -x

EXENV_VERSION_FILE="$1"
EXENV_VERSION="$2"

if [ -z "$EXENV_VERSION" ] || [ -z "$EXENV_VERSION_FILE" ]; then
  exenv-help --usage version-file-write >&2
  exit 1
fi

# Make sure the specified version is installed.
exenv-prefix "$EXENV_VERSION" >/dev/null

# Write the version out to disk.
echo "$EXENV_VERSION" > "$EXENV_VERSION_FILE"
