#!/usr/bin/env bash
#
# Summary: Set or show the local application-specific Elixir version
#
# Usage: exenv local <version>
#        exenv local --unset
#
# Sets the local application-specific Elixir version by writing the
# version name to a file named `.elixir-version'.
#
# When you run a Elixir command, exenv will look for a `.elixir-version'
# file in the current directory and each parent directory. If no such
# file is found in the tree, exenv will use the global Elixir version
# specified with `exenv global'. A version specified with the
# `EXENV_VERSION' environment variable takes precedence over local
# and global versions.
#
# <version> should be a string matching a Elixir version known to exenv.
# The special version string `system' will use your default system Elixir.
# Run `exenv versions' for a list of available Elixir versions.

set -e
[ -n "$EXENV_DEBUG" ] && set -x

# Provide exenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec exenv-versions --bare
fi

EXENV_VERSION="$1"

if [ "$EXENV_VERSION" = "--unset" ]; then
  rm -f .elixir-version
elif [ -n "$EXENV_VERSION" ]; then
  exenv-version-file-write .elixir-version "$EXENV_VERSION"
else
  if version_file="$(exenv-version-file "$PWD")"; then
    exenv-version-file-read "$version_file"
  else
    echo "exenv: no local version configured for this directory" >&2
    exit 1
  fi
fi
