#!/usr/bin/env bash
# Summary: List hook scripts for a given exenv command
# Usage: exenv hooks <command>

set -e
[ -n "$EXENV_DEBUG" ] && set -x

# Provide exenv completions
if [ "$1" = "--complete" ]; then
  echo exec
  echo rehash
  echo version-name
  echo version-origin
  echo which
  exit
fi

EXENV_COMMAND="$1"
if [ -z "$EXENV_COMMAND" ]; then
  exenv-help --usage hooks >&2
  exit 1
fi

if ! enable -f "${BASH_SOURCE%/*}"/exenv-realpath.dylib realpath 2>/dev/null; then
  if [ -n "$EXENV_NATIVE_EXT" ]; then
    echo "exenv: failed to load \`realpath' builtin" >&2
    exit 1
  fi
READLINK=$(type -p greadlink readlink | head -1)
if [ -z "$READLINK" ]; then
  echo "exenv: cannot find readlink - are you missing GNU coreutils?" >&2
  exit 1
fi

resolve_link() {
  $READLINK "$1"
}

realpath() {
  local cwd="$PWD"
  local path="$1"
  local name

  while [ -n "$path" ]; do
    name="${path##*/}"
    [ "$name" = "$path" ] || cd "${path%/*}"
    path="$(resolve_link "$name" || true)"
  done

  echo "${PWD}/$name"
  cd "$cwd"
}
fi

IFS=: hook_paths=($EXENV_HOOK_PATH)

shopt -s nullglob
for path in "${hook_paths[@]}"; do
  for script in "$path/$EXENV_COMMAND"/*.bash; do
    realpath "$script"
  done
done
shopt -u nullglob
