#!/usr/bin/env bash
# Usage: exenv completions <command> [arg1 arg2...]

set -e
[ -n "$EXENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  exenv-help --usage completions >&2
  exit 1
fi

# Provide exenv completions
if [ "$COMMAND" = "--complete" ]; then
  exec exenv-commands
fi

COMMAND_PATH="$(command -v "exenv-$COMMAND" || command -v "exenv-sh-$COMMAND")"

# --help is provided automatically
echo --help

if grep -iE "^([#%]|--|//) provide exenv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
